### ISSUE TITLE
Trouble Rendering the Layout with colorpreference 

### ISSUE THREAD

**Issue by parmarravi** [kizitonwose/colorpreference#11]
I am having a trouble rendering the layout when editing it .This is the error log i am getting .How do i fix it ?
> java.lang.NullPointerException
> 	at com.kizitonwose.colorpreference.ColorUtils.setColorViewValue(ColorUtils.java:22)
> 	at com.kizitonwose.colorpreference.ColorPreference.onBindView(ColorPreference.java:60)
> 	at android.preference.Preference.getView_Original(Preference.java:559)
> 	at android.preference.Preference_Delegate.getView(Preference_Delegate.java:44)
> 	at android.preference.Preference.getView(Preference.java:556)
> 	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
> 	at android.widget.AbsListView.obtainView(AbsListView.java:2365)
> 	at android.widget.ListView.makeAndAddView(ListView.java:2052)
> 	at android.widget.ListView.fillDown(ListView.java:786)
> 	at android.widget.ListView.fillFromTop(ListView.java:847)
> 	at android.widget.ListView.layoutChildren(ListView.java:1826)
> 	at android.widget.AbsListView.onLayout(AbsListView.java:2164)
> 	at android.view.View.layout_Original(View.java:19659)
> 	at android.view.View_Delegate.layout(View_Delegate.java:91)
> 	at android.view.View.layout(View.java:19645)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> 	at android.view.View.layout_Original(View.java:19659)
> 	at android.view.View_Delegate.layout(View_Delegate.java:91)
> 	at android.view.View.layout(View.java:19645)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
> 	at android.view.View.layout_Original(View.java:19659)
> 	at android.view.View_Delegate.layout(View_Delegate.java:91)
> 	at android.view.View.layout(View.java:19645)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> 	at android.view.View.layout_Original(View.java:19659)
> 	at android.view.View_Delegate.layout(View_Delegate.java:91)
> 	at android.view.View.layout(View.java:19645)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
> 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
> 	at android.view.View.layout_Original(View.java:19659)
> 	at android.view.View_Delegate.layout(View_Delegate.java:91)
> 	at android.view.View.layout(View.java:19645)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
> 	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:346)
> 	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
> 	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
> 	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:544)
> 	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:678)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by kizitonwose** [comment]
This is fixed in version [1.1.0](https://github.com/kizitonwose/colorpreference/releases/tag/1.1.0)
