### ISSUE TITLE
com.kizitonwose.colorpreferencecompat Not allowed ?

### ISSUE THREAD

**Issue by parmarravi** [kizitonwose/colorpreference#12]
com.kizitonwose.colorpreferencecompat.ColorPreferenceCompat Not allowed . The Code in xml is throwing me this error .How to remove it .
The Dialog box is working in mobile phone but i want to remove this error .I am not able to get this error in ColorPreference.The problem is with compat version .

```
<com.kizitonwose.colorpreferencecompat.ColorPreferenceCompat
            android:defaultValue="@color/Color_default"
            android:icon="@drawable/ic_color_black_24dp"
            android:key="@string/pref_ColorPickKey"
            android:title="@string/Color_Select"
            app:showDialog="false" />
```

**Comment by kizitonwose** [comment]
I guess the root tag of your preference XML is presently `PreferenceScreen`. 
You need to change it to `android.support.v7.preference.PreferenceScreen`. This should fix it.

**Comment by parmarravi** [comment]
I have used   androidx.preference:preference:1.0.0  library that  is migrated from com.android.support:preference-v7 library .So by default i should able to see the PreferenceScreen but i am not able to see it .Even adding android.support.v7.preference.PreferenceScreen.  is not helping . 
Is it a bug from android  X or something in android studio, i am not able to find it out ?

**Comment by kizitonwose** [comment]
Try using: `androidx.preference.PreferenceScreen`

**Comment by kizitonwose** [comment]
I'll close the issue since it's not directly from the library.
