### ISSUE TITLE
Pick "dual" color

### ISSUE THREAD

**Issue by mueller-ma** [kizitonwose/colorpreference#15]
Hey,
I'm searching for a color picker that can contain entries consisting of two colors. I want to use it as a theme picker and have some themes with only one color (only blue) and some themes with two colors, e. g. the default material theme (primary color is blue and and accent one is pink).
Proposal: `app:colorChoices` can contain values like `#0000ff|#ff00d0` and the color picker displays a circle (or square) half blue, half pink. `getValue()` can return the values as int Array or as `Pair<Integer, Integer>`.

**Comment by kizitonwose** [comment]
This is outside the scope of the library. However, you can fork the project and add the required features for your specific use case.
