### ISSUE TITLE
java.lang.ClassCastException: com.kizitonwose.colorpreference.ColorPreference cannot be cast to androidx.preference.Preference

### ISSUE THREAD

**Issue by obama** [kizitonwose/colorpreference#17]
Error: ` Caused by: java.lang.ClassCastException: com.kizitonwose.colorpreference.ColorPreference cannot be cast to androidx.preference.Preference
        at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:242)`

`<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:android="http://schemas.android.com/apk/res/android">
....
<com.kizitonwose.colorpreference.ColorPreference
                android:defaultValue="@color/colorPrimary"
                android:key="setting_fit_background_fixed_color_value"
                android:title="Fixed Color" />
...`

im using `implementation 'androidx.preference:preference:1.1.1'`

**Comment by kizitonwose** [comment]
If using AndroidX, you need to use:

`implementation 'com.github.kizitonwose.colorpreference:support:<latest-version>'
`

and 

```xml
<androidx.preference.PreferenceScreen> 

	<com.kizitonwose.colorpreferencecompat.ColorPreferenceCompat
		android:defaultValue="@color/color_default"
		android:key="@string/pref_key" />
	
    <androidx.preference.SwitchPreferenceCompat
		... />
	
	<androidx.preference.SwitchPreferenceCompat
		... />
		
</androidx.preference.PreferenceScreen>
```
