### ISSUE TITLE
build.gradle fail

### ISSUE THREAD

**Issue by chitgoks** [kizitonwose/colorpreference#19]
Using implementation 'com.github.kizitonwose.colorpreference:core:1.1.0', even tried support. I get this

Failed to resolve: com.github.kizitonwose.colorpreference:core:1.1.0
<a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Affected Modules: <a href="openFile:......../app/build.gradle">app</a>

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.kizitonwose.colorpreference:core:1.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/kizitonwose/colorpreference/core/1.1.0/core-1.1.0.pom
       - https://jcenter.bintray.com/com/github/kizitonwose/colorpreference/core/1.1.0/core-1.1.0.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by zhaoxiaoge** [comment]
Hello, have you solved this problem? I have also encountered this problem. The download failed

Error:(30, 13) Failed to resolve: com.github.kizitonwose.colorpreference:core:1.1.0

**Comment by chitgoks** [comment]
seems not. i didnt use this anymore.

**Comment by timjbrown** [comment]
I've run into the same issue. I followed the gradle instructions and got gradle build failure. Could not find com.github.kizitonwose:colorpreference:1.1.0. Any answer on this? Is this project still supported? Not sure if it's dead.

Step 1. Add the JitPack repository to your build file
allprojects {
repositories {
	...
	maven { url 'https://jitpack.io' }
}
}

Step 2. Add the dependency
dependencies {
implementation 'com.github.kizitonwose:colorpreference:1.1.0'
}
