### ISSUE TITLE
Update SDK to 27

### ISSUE THREAD

**Issue by gsantner** [kizitonwose/colorpreference#5]
Hi there, I wanted to point out that SDK27 is already out, and supportlib is at 27.0.0.1.

This library is not include-able currently because of this, so a workaround is needed until fix.

```
    configurations.all {
        resolutionStrategy.force "com.android.support:preference-v7:${version_library_appcompat}"
        resolutionStrategy.force "com.android.support:design:${version_library_appcompat}"
        resolutionStrategy.force "com.android.support:cardview-v7:${version_library_appcompat}"
        resolutionStrategy.force "com.android.support:support-v13:${version_library_appcompat}"
    }
```

**Comment by kizitonwose** [comment]
The last release was a bit early. I'll update support libs and release again ASAP.

**Comment by kizitonwose** [comment]
Version 1.0.5 is out with updated support libraries, I'll now close this issue.

**Comment by gsantner** [comment]
thanks! is the lib already available from mvn repos?

**Comment by kizitonwose** [comment]
Yes. Just update the version number and you're all set.
